site_name: qlient-aiohttp
site_url: https://qlient-org.github.io/python-qlient-aiohttp/
site_description: A fast and modern graphql client library designed with simplicity in mind.

strict: false

repo_name: qlient-org/python-qlient-aiohttp
repo_url: https://github.com/qlient-org/python-qlient-aiohttp

theme:
  name: 'material'
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
      secondary: cyan
      accent: cyan
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: black
      secondary: cyan
      accent: cyan

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.extra

plugins:
  - include-markdown
  - search